#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

postgres_ready() {
python << END
import sys
import os
import psycopg2

try:
    psycopg2.connect(
        dbname=os.environ.get("POSTGRES_DB", "postgres"),
        user=os.environ.get("POSTGRES_USER", "postgres"),
        password=os.environ.get("POSTGRES_PASSWORD", "postgres"),
        host=os.environ.get("POSTGRES_HOST", "postgres"),
        port=os.environ.get("POSTGRES_POST", 5432),
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)
END
}

until postgres_ready; do
 >&2 echo "Waiting for PostgreSQL to become available....:-("
 sleep 1
done
>&2 echo "PostgreSQL is ready!!!!...:-)"

exec "$@"