#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

python3 manage.py makemigrations --no-input
python3 manage.py migrate --no-input
python3 manage.py collectstatic --no-input
#python3 manage.py runserver 0.0.0.0:8000
gunicorn instagram.wsgi:application --name instagram --workers 3 --bind 0.0.0.0:8000 --log-level=debug