# Generated by Django 3.2.12 on 2022-04-10 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
